### PR TITLE
Code Refactor - Naming Convention / spacing

### PR DESCRIPTION
**Pull request by enkodellc**
- Breaking Changes
- With Resharper I was able to quickly convert from 4 space tab to 2 space tab.
- I  went through the project files set the proper methods names {Get, GetAll, Delete, Create, Add, Update}  Removing the redundant "ById" convert "GetSpecific" -> "Get", fixed plurals, verbs in function names.
- Cleaned up some of the flags ReSharper suggested. Tried to limit them to simple fixes that ReSharper fixes and won't affect the code.
- Reviewed all files and the redundant directives are removed.
- This would be a lot of work to add [Obsolete tags to the methods that changed names] so I did not do this but if it is something that you feel is a requirement I will let you tackle it after I push it to the new branch.

### CODE REVIEW

**Comment by brandonseydel** [comment]
Removing async from method names is not only going to be confusing, but it is against standards.
http://msdn.microsoft.com/en-us/library/hh191443.aspx#BKMK_NamingConvention

**Comment by enkodellc** [comment]
Thanks @brandonseydel I will refactor them back in: http://stackoverflow.com/questions/15951774/does-the-use-of-the-async-suffix-in-a-method-name-depend-on-whether-the-async

**Comment by enkodellc** [comment]
@brandonseydel One issue I have seen while renaming the methods is that I think we should consistently use "Insert" instead of the "Add" or "Create". Your thoughts?
Have you considered contributing to the project? Maybe help with the wikis or writing tests?

**Comment by shahriarhossain** [comment]
@enkodellc : Since the branch 2 contains some breaking change, so I prefer to push it in a particular date. What I wanted to say, is that we will update the ReadMe file and announce there the changes that we  are planning to make. 
Plus in the next release you can expect few more things. 
One. As soon someone download it from nuget s/he will see a new html page popping in their VS displaying info like(what it is, how to use it, how to create a new issue, how to contribute, who are the contributes etc).
Two. VS Intellisense support.

**Comment by shahriarhossain** [comment]
@brandonseydel : Thanks for pointing us the proper document.

**Comment by enkodellc** [comment]
@shahriarhossain  we can push it to the second branch (CodeRefactor) as that will not affect the master branch. This will allow others to easily review and submit their own PR's against this branch.  This should allow us to update the readme / Wiki for that branch specifically.

http://stackoverflow.com/questions/14783486/github-wiki-select-branch-dispalyed-on-github

I am totally fine with setting a merge date to master. I just feel strongly we should push this to the new branch so that others can review and update it as well. 

At the moment I am close to finishing my updates to the wrapper so once you agree to push I can start updating the Wiki on the new branch.

**Pull request merged**
